<a href="https://colab.research.google.com/github/SueYavuz/statistic/blob/main/ARRAY_creation_and_slicing_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
 my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

get dimensions

In [4]:
my_array.ndim

1

In [5]:
my_array.shape

(3,)

In [6]:
my_array.dtype

dtype('int64')

In [7]:
my_array.itemsize

8

In [8]:
my_array.size

3

# **Slicing**

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
a[1,5]

13

In [11]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,2]

array([ 3, 10])

In [13]:
a[0,1:6:2]

array([2, 4, 6])

In [14]:
a[1,5]=20

In [15]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [16]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [17]:
b[:,1,1]

array([4])

In [18]:
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [19]:
b[:,1,:]

array([[3, 4]])

In [21]:
#spesfik olarak deger verilirse deger slicing noktasiyla degisir
b[:,1,:]=[9,9]

In [22]:
b

array([[[1, 2],
        [9, 9],
        [5, 6],
        [7, 8]]])

# **ones, zeros, full**

In [23]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
#istedigin degeri yazdirabiliyorsun
#virgulden sonra yazip
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
np.arange(4,10).reshape(3,2)

array([[4, 5],
       [6, 7],
       [8, 9]])