<a href="https://colab.research.google.com/github/SueYavuz/statistic/blob/main/Correlation_and_Covariance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas Correlation Calculation**

example

In [8]:
import pandas as pd
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method to calculate Pearson's r correlation.

In [9]:
from scipy import stats
r= stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

Call the relevant method to calculate **Spearman's rho correlation**.

In [10]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

example

In [ ]:
#with scipy library
from scipy import stats

print("correlation coefficient and p-value: ", stats.pearsonr(temp, number_of_people))

correlation coefficient and p-value:  (0.9087693361896165, 0.012104893069677013)


# **NumPy Correlation Calculation**
Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arange()



In [2]:
import numpy as np

x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use np.array() to create a second array y containing 10 arbitrary integers.

In [3]:
y = np.array([0,1,2,3,4,5,6,7,8,9])
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [12]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

example

In [16]:
temp=[93,84,82,78,98,70]

number_of_people=[13,10, 11, 8, 15, 9]

print("covariance: ", np.cov(temp, number_of_people))

covariance:  [[102.56666667  24.        ]
 [ 24.           6.8       ]]


In [17]:
print("correlation: ", np.corrcoef(temp, number_of_people))

correlation:  [[1.         0.90876934]
 [0.90876934 1.        ]]
